### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Auxeras** [SirCmpwn/fosspay#4]
Hi,

I am part of a french association and we would like to use fosspay to process our donations. However for that purpose we need a french version of the interface. I am interested in developing one, and I would like to discuss with you how best to do it!

Do you think simply creating alternate versions of the existing template files (i.e. a login-fr.html file alongside login.html) is the way to go for this, or should we go for more structural changes?

Cheers,
Lina

**Comment by SirCmpwn** [comment]
Hi! fosspay is designed to support user overrides of the templates. When you install fosspay to your site, you should populate the `overrides` directory with files of the same name as the templates in the `templates` directory, and they will be used instead. Once you have a full translation feel free to send a pull request adding it `contrib/fr/` :)

**Comment by Auxeras** [comment]
Got it, I'll make sure to do so once it's ready c: !

**Comment by Auxeras** [comment]
We encountered a problem while translating : the override system works for all the `template` HTML files, but there's a little bit of english hardcoded in the `scripts/index.js`  which can't be handled this way. We fixed it manually on our instance but couldn't this be solved more elegantly?

**Comment by SirCmpwn** [comment]
How about adding something like this to the templates?

```
const i18n = {
    "Monthly Donation": "毎月の寄付",
    "One-time Donation": "一度の寄付",
    ...
};
```

Then updating the JavaScript accordingly:

```
donation.type == "monthly" ? i18n["Monthly Donation"] : i18n["One-time Donation"]
```

**Comment by Auxeras** [comment]
Okay, we made it work with this solution.

However, on last thing : the `emails` folder also contains files with hardcoded english (that we replaced already). Wouldn't the easiest solution be to submit a `contrib/fr` folder containing both an `overrides` subfolder and an `emails` subfolder which would replace the default ones?

If that's OK we will be ready to send a pull request soon.

**Comment by SirCmpwn** [comment]
:+1:

**Comment by SirCmpwn** [comment]
Seems like this is done, thanks for your help!
